// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZNXQXITva7nFR5n5EADEOI1Cw6eXRBUQ',
    appId: '1:344110366088:web:29b45cbee0333e79754e3d',
    messagingSenderId: '344110366088',
    projectId: 'dclic-market-93bdb',
    authDomain: 'dclic-market-93bdb.firebaseapp.com',
    storageBucket: 'dclic-market-93bdb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV1CM4CGrlcIVx7oTyVR-3bSFkqM-3Z0Y',
    appId: '1:344110366088:android:5b2c578888bd2f37754e3d',
    messagingSenderId: '344110366088',
    projectId: 'dclic-market-93bdb',
    storageBucket: 'dclic-market-93bdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcci4o_n0mDkOcZMUPtlG6LfVK0HInfYY',
    appId: '1:344110366088:ios:0e325db391baebd0754e3d',
    messagingSenderId: '344110366088',
    projectId: 'dclic-market-93bdb',
    storageBucket: 'dclic-market-93bdb.firebasestorage.app',
    iosBundleId: 'com.example.agbannon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcci4o_n0mDkOcZMUPtlG6LfVK0HInfYY',
    appId: '1:344110366088:ios:0e325db391baebd0754e3d',
    messagingSenderId: '344110366088',
    projectId: 'dclic-market-93bdb',
    storageBucket: 'dclic-market-93bdb.firebasestorage.app',
    iosBundleId: 'com.example.agbannon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZNXQXITva7nFR5n5EADEOI1Cw6eXRBUQ',
    appId: '1:344110366088:web:13672d288b49ab13754e3d',
    messagingSenderId: '344110366088',
    projectId: 'dclic-market-93bdb',
    authDomain: 'dclic-market-93bdb.firebaseapp.com',
    storageBucket: 'dclic-market-93bdb.firebasestorage.app',
  );
}
