name: agbannon
description: Application mobile pour les marchands d'Agbannon.

# Version du projet
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Interface utilisateur
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  lottie: ^2.4.0
  flutter_spinkit: ^5.2.0
  intl: ^0.18.1
  image_picker: ^1.0.0
  photo_view: ^0.14.0
  url_launcher: ^6.1.11
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^4.0.4
  flutter_localizations:
    sdk: flutter

  # Architecture et état
  provider: ^6.0.5
  flutter_riverpod: ^2.3.6
  shared_preferences: ^2.1.2
  get_it: ^7.6.0

  # Firebase et base de données
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.2.1
  firebase_messaging: ^14.6.1
  firebase_analytics: ^10.4.1
  firebase_crashlytics: ^3.3.1

  # Gestion des paiements
  flutter_stripe: ^9.2.0
  pay: ^1.1.1
  
  # Autres utilités
  uuid: ^3.0.7
  path: ^1.8.3
  http: ^1.0.0
  connectivity_plus: ^4.0.1
  device_info_plus: ^9.0.2
  package_info_plus: ^4.0.2
  permission_handler: ^10.2.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  flutter_local_notifications: ^14.1.0
  image_cropper: ^5.0.0
  share_plus: ^7.0.2
  flutter_barcode_scanner: ^2.0.0
  flutter_rating_bar: ^4.0.1
  fl_chart: ^0.63.0
  printing: ^5.10.4
  pdf: ^3.10.1
  path_provider: ^2.0.15
  carousel_slider: ^4.2.1
  flutter_secure_storage: ^8.0.0
  easy_debounce: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.4
  mockito: ^5.4.1
  integration_test:
    sdk: flutter

# Configuration Flutter
flutter:
  # Activer la prise en charge du matériel design
  uses-material-design: true

  # Ressources d'actifs
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/

  # Polices personnalisées
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700