// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAclJOsAjpHW31-JqO225Vkuo1BCNBVXaM',
    appId: '1:803457253528:web:52b3e52c7c61ac8192d0ed',
    messagingSenderId: '803457253528',
    projectId: 'dclicmarket-3ee30',
    authDomain: 'dclicmarket-3ee30.firebaseapp.com',
    storageBucket: 'dclicmarket-3ee30.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvtpjW9_rrbnZRyrb-nl6xnSrIM6M_oRQ',
    appId: '1:803457253528:android:f2dd98ed265bf80c92d0ed',
    messagingSenderId: '803457253528',
    projectId: 'dclicmarket-3ee30',
    storageBucket: 'dclicmarket-3ee30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuelShnDpYWOr2yOWEWf_xJscR4xDLIyM',
    appId: '1:803457253528:ios:bb7324627736337292d0ed',
    messagingSenderId: '803457253528',
    projectId: 'dclicmarket-3ee30',
    storageBucket: 'dclicmarket-3ee30.firebasestorage.app',
    iosBundleId: 'com.example.ahigan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuelShnDpYWOr2yOWEWf_xJscR4xDLIyM',
    appId: '1:803457253528:ios:bb7324627736337292d0ed',
    messagingSenderId: '803457253528',
    projectId: 'dclicmarket-3ee30',
    storageBucket: 'dclicmarket-3ee30.firebasestorage.app',
    iosBundleId: 'com.example.ahigan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAclJOsAjpHW31-JqO225Vkuo1BCNBVXaM',
    appId: '1:803457253528:web:a4914fd98ca4b2a392d0ed',
    messagingSenderId: '803457253528',
    projectId: 'dclicmarket-3ee30',
    authDomain: 'dclicmarket-3ee30.firebaseapp.com',
    storageBucket: 'dclicmarket-3ee30.firebasestorage.app',
  );
}
